config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :pages
  resources :events
  resources :timelines
  resources :users

  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :timelines
    validates :login, presence: true, uniqueness: true
    validates :last_name, presence: true
    validates :first_name, presence: true
    validates :middle_name, presence: true
    validates :birthdate, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    if current_user
      if current_user.id == 1
        @users = User.all
      else
        @users = User.where(id: current_user.id)
      end
    else
      @users = User.all
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.role = 1
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:login, :password, :first_name, :last_name, :middle_name, :birthdate)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="d-flex justify-content-center h-100">
<div class="card">
			<div class="card-body">
				<form>
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text">Логин</span>
						</div>
            <%= form.text_field :login %>
					</div>
          <div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text">Пароль</span>
						</div>
            <%= form.text_field :password %>
					</div>
          <div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text">Фамилия</span>
						</div>
            <%= form.text_field :last_name %>
					</div>
          <div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text">Имя</span>
						</div>
            <%= form.text_field :first_name %>
					</div>
          <div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text">Отчество</span>
						</div>
            <%= form.text_field :middle_name %>
					</div>
          <div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text">Дата рождения</span>
						</div>
            <%= form.date_select :birthdate, :start_year=>Date.today.year - 100,:end_year=>Date.today.year %>
					</div>
					<div class="form-group">
             <%= form.submit "Отправить" %>
					</div>
				</form>
			</div>
		</div>
    </div>

    <% end %>

app/views/users/edit.html.erb
<h1>Редактирование автора</h1>

<%= render 'form', user: @user %>

<%= link_to 'Показать', @user %> |
<%= link_to 'Назад', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Авторы</h1>

<table class="table table-primary">
  <thead>
    <tr>
      <th>Логин</th>
      <th>Роль</th>
      <th>Имя</th>
      <th>Фамилия</th>
      <th>Отчество</th>
      <th>Дата рождения</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.login %></td>
        <td><%= user.role %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.middle_name %></td>
        <td><%= user.birthdate %></td>
        <td><%= link_to '<i class="fa fa-search"></i>'.html_safe, user %></td>
        <td><%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_page_path(user) %></td>
        <td><%= link_to '<i class="fa fa-trash"></i>'.html_safe, user, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Создать нового автора', new_user_path %>

app/views/users/new.html.erb
<h1 class="d-flex justify-content-center h-100">Новый автор</h1>

<%= render 'form', user: @user %>

<%= link_to 'Назад', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Логин:</strong>
  <%= @user.login %>
</p>

<p>
  <strong>Пароль:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Имя:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Фамилия:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Отчество:</strong>
  <%= @user.middle_name %>
</p>

<p>
  <strong>Дата рождения:</strong>
  <%= @user.birthdate %>
</p>

<%= link_to 'Изменить', edit_user_path(@user) %> |
<%= link_to 'Назад', users_path %>