config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :pages
  resources :events
  resources :timelines
  resources :users

  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :timeline
  validates :title, presence: true
  validates :create_datetime, presence: true
  validates :description, presence: true
  validates :event_type, presence: true
  validates :timeline_id, presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
    @timelines = Timeline.where(user_id: current_user.id)
  end

  # GET /events/1/edit
  def edit
    @timelines = Timeline.where(user_id: current_user.id)
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :create_datetime, :description, :event_type, :timeline_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Заголовок
    <%= form.text_field :title %>
  </div>

  <div class="field">
    Дата события
    <%= form.datetime_select :create_datetime, :start_year=>Date.today.year - 100,:end_year=>Date.today.year %>
  </div>

  <div class="field">
    Описание
    <%= form.text_area :description %>
  </div>

  <div class="field">
    Тип
    <%= form.text_field :event_type %>
  </div>

  <div class="field">
    Линия времени
    <%= form.collection_select :timeline_id, @timelines, :id, :title %>
  </div>

  <div class="actions">
    <%= form.submit "Отправить"%>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Редактирование события</h1>

<%= render 'form', event: @event %>

<%= link_to 'Показать', @event %> |
<%= link_to 'Назад', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>События</h1>

<table class="table table-primary">
  <thead>
    <tr>
      <th>Заголовок</th>
      <th>Дата события</th>
      <th>Описание</th>
      <th>Тип</th>
      <th>Линия времени</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.create_datetime %></td>
        <td><%= event.description %></td>
        <td><%= event.event_type %></td>
        <td><%= event.timeline.title %></td>
        <td><%= link_to '<i class="fa fa-search"></i>'.html_safe, event %></td>
        <td><%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_page_path(event) %></td>
        <td><%= link_to '<i class="fa fa-trash"></i>'.html_safe, event, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Новое событие', new_event_path %>

app/views/events/new.html.erb
<h1>Новое событие</h1>

<%= render 'form', event: @event %>

<%= link_to 'Назад', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Заголовок:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Дата события:</strong>
  <%= @event.create_datetime %>
</p>

<p>
  <strong>Описание:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Тип:</strong>
  <%= @event.event_type %>
</p>

<p>
  <strong>Линия времени:</strong>
  <%= @event.timeline.title %>
</p>

<%= link_to 'Новое событие', new_event_path %>
<%= link_to 'Изменить', edit_event_path(@event) %> |
<%= link_to 'Назад', events_path %>