config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :pages
  resources :events
  resources :timelines
  resources :users

  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/timeline.rb
class Timeline < ApplicationRecord
  belongs_to :user
  has_many :events
  validates :title, presence: true
  validates :description, presence: true
end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
  before_action :set_timeline, only: [:show, :edit, :update, :destroy]

  # GET /timelines
  # GET /timelines.json
  def index
    if current_user
      if current_user.id == 1
        @timelines = Timeline.all
      else
        @timelines = Timeline.where(user_id: current_user.id)
      end
    else
      @timelines = Timeline.all
    end
  end

  # GET /timelines/1
  # GET /timelines/1.json
  def show
    @events = Event.where(timeline_id: @timeline.id)
  end

  # GET /timelines/new
  def new
    @timeline = Timeline.new
  end

  # GET /timelines/1/edit
  def edit
  end

  # POST /timelines
  # POST /timelines.json
  def create
    @timeline = Timeline.new(timeline_params)
    @timeline.user_id = current_user.id

    respond_to do |format|
      if @timeline.save
        format.html { redirect_to @timeline, notice: 'Линия времени успешно создана.' }
        format.json { render :show, status: :created, location: @timeline }
      else
        format.html { render :new }
        format.json { render json: @timeline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /timelines/1
  # PATCH/PUT /timelines/1.json
  def update
    respond_to do |format|
      if @timeline.update(timeline_params)
        format.html { redirect_to @timeline, notice: 'Timeline was successfully updated.' }
        format.json { render :show, status: :ok, location: @timeline }
      else
        format.html { render :edit }
        format.json { render json: @timeline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timelines/1
  # DELETE /timelines/1.json
  def destroy
    @timeline.destroy
    respond_to do |format|
      format.html { redirect_to timelines_url, notice: 'Timeline was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timeline
      @timeline = Timeline.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def timeline_params
      params.require(:timeline).permit(:title, :description, :user_id)
    end
end

app/helpers/timelines_helper.rb
module TimelinesHelper
end

app/views/timelines/_form.html.erb
<%= form_with(model: timeline, local: true) do |form| %>
  <% if timeline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(timeline.errors.count, "error") %> prohibited this timeline from being saved:</h2>

      <ul>
      <% timeline.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Заголовок
    <%= form.text_field :title %>
  </div>

  <div class="field">
    Описание
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit "Создать"%>
  </div>
<% end %>

app/views/timelines/edit.html.erb
<h1>Редактирование временной линии</h1>

<%= render 'form', timeline: @timeline %>

<%= link_to 'Показать', @timeline %> |
<%= link_to 'Назад', timelines_path %>

app/views/timelines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Линии времени</h1>

<table class="table table-primary">
  <thead>
    <tr>
      <th>Заголовок</th>
      <th>Описание</th>
      <th>Автор</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @timelines.each do |timeline| %>
      <tr>
        <td><%= timeline.title %></td>
        <td><%= timeline.description %></td>
        <td><%= timeline.user.last_name + " " + timeline.user.first_name + " " + timeline.user.middle_name%></td>
        <td><%= link_to 'Показать', timeline %></td>
        <td><%= link_to 'Изменить', edit_timeline_path(timeline) %></td>
        <td><%= link_to 'Удалить', timeline, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Новая линия времени', new_timeline_path %>

app/views/timelines/new.html.erb
<h1>Создание новой линии времени</h1>

<%= render 'form', timeline: @timeline %>

<%= link_to 'Назад', timelines_path %>

app/views/timelines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Заголовок:</strong>
  <%= @timeline.title %>
</p>

<p>
  <strong>Описание:</strong>
  <%= @timeline.description %>
</p>

<p>
  <strong>Автор:</strong>
  <%= @timeline.user.login %>
</p>

<div class="qa-message-list" id="wallmessages">
<% @events.sort_by(&:create_datetime).each do |event| %>
<div class="message-item" id="m16">
						<div class="message-inner">
							<div class="message-head clearfix">
								<div class="avatar pull-left">

                <% if event.event_type == 1 %>
                  <img src="https://tasvel.ru/wp-content/uploads/Ikonka-MTS.png">
                <% else %> 
                  <img src="https://ssl.gstatic.com/accounts/ui/avatar_2x.png">
                <% end %>

                </div>
								<div class="user-detail">
									<h5 class="handle"><%= event.title %></h5>
									<div class="post-meta">
										<div class="asker-meta">
											<span class="qa-message-what"></span>
											<span class="qa-message-when">
												<span class="qa-message-when-data"><%= event.create_datetime %></span>
											</span>
											<span class="qa-message-who">
												<span class="qa-message-who-pad">by </span>
											</span>
										</div>
									</div>
								</div>
							</div>
							<div class="qa-message-content">
								<%= event.description %>
							</div>
							<div><%= link_to 'Изменить', edit_event_path(event) %></div>
					</div></div>
    <% end %>	
</div>

<%= link_to 'Новое событие', new_event_path %>